import { useMemo, useState } from 'react'
import { Box, Button, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, ToggleButton, ToggleButtonGroup, Typography, useMediaQuery } from '@mui/material'
import { useData } from '../contexts/DataContext.jsx'
import { formatKs, getToday } from '../utils/storage.js'
import { buildReportAnalysis } from '../domain/reporting.js'

const money = (value) => formatKs(Number(value || 0))
const presets = [{ id: 'today', label: 'ယနေ့' }, { id: 'week', label: 'ယခုအပတ်' }, { id: 'month', label: 'ယခုလ' }, { id: 'year', label: 'ယခုနှစ်' }, { id: 'three', label: '၃ လ' }, { id: 'six', label: '၆ လ' }]
function rangeFor(id) { const today = getToday(); const date = new Date(`${today}T00:00:00`); const start = new Date(date); if (id === 'week') start.setDate(date.getDate() - 6); if (id === 'month') start.setDate(1); if (id === 'year') start.setMonth(0, 1); if (id === 'three') start.setMonth(date.getMonth() - 2, 1); if (id === 'six') start.setMonth(date.getMonth() - 5, 1); return { from: start.toISOString().slice(0, 10), to: today } }
function Metric({ label, value, tone = '' }) { return <Box className={`report-metric ${tone}`}><Typography>{label}</Typography><strong>{value}</strong></Box> }

export default function BalancePage() {
  const mobile = useMediaQuery('(max-width:899px)'); const { data } = useData(); const [preset, setPreset] = useState('today'); const [range, setRange] = useState(() => rangeFor('today')); const [search, setSearch] = useState(''); const [sort, setSort] = useState('sold'); const [supplierOpen, setSupplierOpen] = useState('')
  const report = useMemo(() => buildReportAnalysis(data, range.from, range.to), [data, range])
  const products = useMemo(() => report.products.filter((row) => row.name.toLowerCase().includes(search.trim().toLowerCase())).sort((a, b) => sort === 'profit' ? b.profit - a.profit : sort === 'stock' ? a.stockQty - b.stockQty : b.soldQty - a.soldQty), [report.products, search, sort])
  const setQuickRange = (id) => { setPreset(id); setRange(rangeFor(id)) }
  return <Box className="page-stack report-dashboard-page">
    <Box className="report-toolbar"><ToggleButtonGroup exclusive value={preset} onChange={(_, id) => id && setQuickRange(id)} size="small" className="report-presets">{presets.map((item) => <ToggleButton key={item.id} value={item.id}>{item.label}</ToggleButton>)}</ToggleButtonGroup><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField type="date" size="small" label="မှ" value={range.from} onChange={(e) => { setPreset(''); setRange({ ...range, from: e.target.value }) }} slotProps={{ inputLabel: { shrink: true } }} /><TextField type="date" size="small" label="ထိ" value={range.to} onChange={(e) => { setPreset(''); setRange({ ...range, to: e.target.value }) }} slotProps={{ inputLabel: { shrink: true } }} /></Stack></Box>
    <Box className="report-metric-grid"><Metric label="ရောင်းရငွေ" value={money(report.financial.revenue)} tone="income" /><Metric label="ကုန်ပစ္စည်းကုန်ကျစရိတ်" value={money(report.financial.costOfGoods)} /><Metric label="အကြမ်းအမြတ်" value={money(report.financial.grossProfit)} tone="income" /><Metric label="ကုန်ကျစရိတ်" value={money(report.financial.operatingExpenses)} tone="expense" /><Metric label="အသားတင်အမြတ်" value={money(report.financial.netProfit)} tone={report.financial.netProfit >= 0 ? 'income' : 'expense'} /><Metric label="ရရန်အကြွေး" value={money(report.receivable)} tone="warning" /><Metric label="ပေးရန်ကုန်ကြွေး" value={money(report.payable)} tone="warning" /><Metric label="လက်ရှိ stock တန်ဖိုး" value={money(report.stockValue)} /></Box>
    <Paper variant="outlined" className="report-section"><Typography variant="h6" fontWeight={900}>အရောင်းနှင့်အမြတ် ခွဲခြမ်းစိတ်ဖြာမှု</Typography><Box className="report-profit-bars">{[['ရောင်းရငွေ', report.financial.revenue, 'income'], ['ကုန်ကျစရိတ်', report.financial.operatingExpenses, 'expense'], ['အသားတင်အမြတ်', report.financial.netProfit, report.financial.netProfit >= 0 ? 'income' : 'expense']].map(([label, value, tone]) => <Box key={label} className="report-bar-row"><Typography>{label}</Typography><Box className="report-bar-track"><Box className={`report-bar ${tone}`} sx={{ width: `${Math.min(100, Math.abs(Number(value || 0)) / Math.max(1, report.financial.revenue) * 100)}%` }} /></Box><Typography fontWeight={800}>{money(value)}</Typography></Box>)}</Box></Paper>
    <Paper variant="outlined" className="report-section"><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={1}><Box><Typography variant="h6" fontWeight={900}>ကုန်ပစ္စည်း ခွဲခြမ်းစိတ်ဖြာမှု</Typography><Typography color="text.secondary" variant="body2">ဝယ်ယူမှု၊ အရောင်း၊ အမြတ်နှင့် လက်ရှိ stock</Typography></Box><Stack direction="row" gap={1}><TextField size="small" label="ပစ္စည်းရှာရန်" value={search} onChange={(e) => setSearch(e.target.value)} /><TextField select size="small" label="စီရန်" value={sort} onChange={(e) => setSort(e.target.value)} sx={{ minWidth: 130 }}><option value="sold">အရောင်းများ</option><option value="profit">အမြတ်များ</option><option value="stock">လက်ကျန်နည်း</option></TextField></Stack></Stack>{mobile ? <Box className="report-mobile-list">{products.map((row) => <Paper key={row.key} variant="outlined" className="report-product-card"><Stack direction="row" justifyContent="space-between"><Typography fontWeight={900}>{row.name}</Typography><Typography className={row.profit >= 0 ? 'finance-income' : 'finance-expense'} fontWeight={900}>{money(row.profit)}</Typography></Stack><Typography variant="body2">ဝယ် {row.boughtQty} ခု · ရောင်း {row.soldQty} ခု · လက်ကျန် {row.stockQty} ခု</Typography><Typography variant="body2">ရောင်းရငွေ {money(row.revenue)} · stock တန်ဖိုး {money(row.stockValue)}</Typography></Paper>)}{!products.length ? <Typography className="finance-empty">ပစ္စည်း record မရှိသေးပါ</Typography> : null}</Box> : <TableContainer><Table size="small"><TableHead><TableRow><TableCell>ပစ္စည်း</TableCell><TableCell align="right">ဝယ်ယူ</TableCell><TableCell align="right">ရောင်းပြီး</TableCell><TableCell align="right">ရောင်းရငွေ</TableCell><TableCell align="right">ကုန်ကျစရိတ်</TableCell><TableCell align="right">အမြတ်</TableCell><TableCell align="right">လက်ကျန်/တန်ဖိုး</TableCell></TableRow></TableHead><TableBody>{products.map((row) => <TableRow key={row.key}><TableCell>{row.name}</TableCell><TableCell align="right">{row.boughtQty} · {money(row.boughtValue)}</TableCell><TableCell align="right">{row.soldQty}</TableCell><TableCell align="right">{money(row.revenue)}</TableCell><TableCell align="right">{money(row.cost)}</TableCell><TableCell align="right" className={row.profit >= 0 ? 'finance-income' : 'finance-expense'}>{money(row.profit)}</TableCell><TableCell align="right">{row.stockQty} · {money(row.stockValue)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}</Paper>
    <Paper variant="outlined" className="report-section"><Typography variant="h6" fontWeight={900}>Supplier ခွဲခြမ်းစိတ်ဖြာမှု</Typography>{report.suppliers.map((row) => <Box key={row.key} className="report-supplier-row"><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography fontWeight={900}>{row.name}</Typography><Typography variant="body2">ပစ္စည်း {row.itemTypes} မျိုး · {row.quantity} ခု · ဝယ်ယူတန်ဖိုး {money(row.value)}</Typography></Box><Button size="small" onClick={() => setSupplierOpen(supplierOpen === row.key ? '' : row.key)}>{supplierOpen === row.key ? 'ပိတ်မည်' : 'အသေးစိတ်'}</Button></Stack>{supplierOpen === row.key ? <Box className="report-supplier-details"><Typography>ပေးပြီး {money(row.paid)} · ပေးရန်ကျန် {money(row.payable)}</Typography>{row.purchases.flatMap((purchase) => purchase.items || []).map((item) => <Typography key={item.id} variant="body2">{item.productName || item.name} · {item.receivedQuantity || item.quantity} ခု · {money(item.lineTotal || Number(item.quantity || 0) * Number(item.unitCost || 0))}</Typography>)}</Box> : null}</Box>)}{!report.suppliers.length ? <Typography className="finance-empty">Supplier purchase record မရှိသေးပါ</Typography> : null}</Paper>
  </Box>
}
