ALTER TABLE "PurchaseReceipt" ADD COLUMN IF NOT EXISTS "note" TEXT;
ALTER TABLE "PurchasePayment" ADD COLUMN IF NOT EXISTS "reversedAt" TIMESTAMP(3);
ALTER TABLE "PurchasePayment" ADD COLUMN IF NOT EXISTS "reversalReason" TEXT;
ALTER TABLE "ShopSetting" ADD COLUMN IF NOT EXISTS "locale" TEXT NOT NULL DEFAULT 'en-MM';
ALTER TABLE "ShopSetting" ADD COLUMN IF NOT EXISTS "timeZone" TEXT NOT NULL DEFAULT 'Asia/Yangon';
