import { useEffect, useState } from "react";
import { useNavigate } from "react-router";
import { Alert, AppBar, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Paper, Stack, TextField, Toolbar, Typography } from "@mui/material";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import ArrowBackRoundedIcon from "@mui/icons-material/ArrowBackRounded";
import CategoryRoundedIcon from "@mui/icons-material/CategoryRounded";
import DeleteRoundedIcon from "@mui/icons-material/DeleteRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import { usePosApi } from "../../hooks/useApiResource";

export default function CategoryManagementPage() { const navigate = useNavigate(); const api = usePosApi(); const [items, setItems] = useState([]); const [draft, setDraft] = useState(""); const [editing, setEditing] = useState(null); const [error, setError] = useState(""); const load = async () => { try { const result = await api.categories.list(); setItems((result.categories || []).map((item) => ({ ...item, count: item._count?.products || 0 }))); setError(""); } catch (requestError) { setError(requestError.message || "Unable to load categories."); } }; useEffect(() => { const timeout = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timeout); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [api]); const close = () => { setDraft(""); setEditing(null); }; const save = async () => { if (!draft.trim()) return; try { if (editing?.id) await api.categories.update(editing.id, { name: draft.trim() }); else await api.categories.create({ name: draft.trim() }); close(); await load(); } catch (requestError) { setError(requestError.message || "Unable to save category."); } }; const remove = async (item) => { try { await api.categories.remove(item.id); await load(); } catch (requestError) { setError(requestError.message || "Unable to delete category."); } }; return <ManagementShell title="Category Management" back={() => navigate("/settings")} button="Add Category" onAdd={() => setEditing({})}>{error && <Alert severity="error">{error}</Alert>}<Stack spacing={2.25}>{items.map((item) => <Paper key={item.id} elevation={2} sx={cardSx}><Box sx={iconSx}><CategoryRoundedIcon /></Box><Box sx={{ minWidth: 0 }}><Typography sx={{ fontSize: 22, fontWeight: 700 }}>{item.name}</Typography><Typography color="text.secondary" sx={{ mt: .25, fontSize: 17 }}>{item.count} {item.count === 1 ? "product" : "products"}</Typography></Box><IconButton aria-label={`Edit ${item.name}`} onClick={() => { setDraft(item.name); setEditing(item); }} sx={{ color: "primary.main" }}><EditRoundedIcon sx={{ fontSize: 31 }} /></IconButton><IconButton aria-label={`Delete ${item.name}`} onClick={() => remove(item)} sx={{ color: "#ef5144" }}><DeleteRoundedIcon sx={{ fontSize: 31 }} /></IconButton></Paper>)}</Stack><Editor open={Boolean(editing)} title={editing?.id ? "Edit Category" : "Add Category"} value={draft} onChange={setDraft} onClose={close} onSave={save} label="Category name" /></ManagementShell>; }
export function ManagementShell({ title, back, button, onAdd, children }) { return <Box sx={{ minHeight: "100dvh", bgcolor: "#f8fafc", pb: 13 }}><AppBar position="sticky" elevation={0} sx={{ bgcolor: "primary.main" }}><Toolbar sx={{ minHeight: 70, display: "grid", gridTemplateColumns: "48px minmax(0,1fr) 48px" }}><IconButton aria-label="Back to settings" onClick={back} sx={{ color: "common.white" }}><ArrowBackRoundedIcon sx={{ fontSize: 32 }} /></IconButton><Typography align="center" sx={{ fontSize: 22, fontWeight: 700 }}>{title}</Typography><Box /></Toolbar></AppBar><Box sx={{ p: { xs: 2.5, sm: 3 }, maxWidth: 720, mx: "auto" }}>{children}</Box><Button variant="contained" startIcon={<AddRoundedIcon />} onClick={onAdd} sx={{ position: "fixed", right: { xs: 2.5, sm: "max(32px, calc((100% - 680px)/2))" }, bottom: 28, minHeight: 58, px: 3, borderRadius: 2.25, bgcolor: "#ff5a2c", boxShadow: "0 5px 12px rgba(255,90,44,.35)", fontSize: 17, fontWeight: 700, textTransform: "none", "&:hover": { bgcolor: "#e94b20" } }}>{button}</Button></Box>; }
export function Editor({ open, title, value, onChange, onClose, onSave, label }) { return <Dialog open={open} onClose={onClose} fullWidth slotProps={{ paper: { sx: { m: 2.5, borderRadius: 2.5, maxWidth: 420 } } }}><DialogTitle fontWeight={700}>{title}</DialogTitle><DialogContent><TextField autoFocus fullWidth label={label} value={value} onChange={(event) => onChange(event.target.value)} sx={{ mt: .5 }} /></DialogContent><DialogActions sx={{ p: 2, pt: 0 }}><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={onSave}>Save</Button></DialogActions></Dialog>; }
const cardSx = { minHeight: 140, p: { xs: 2, sm: 2.75 }, borderRadius: 2.5, display: "grid", gridTemplateColumns: "72px minmax(0,1fr) 48px 48px", alignItems: "center", gap: { xs: 1.25, sm: 2 }, boxShadow: "0 3px 9px rgba(15,23,42,.19)" };
const iconSx = { width: 64, height: 64, borderRadius: "50%", display: "grid", placeItems: "center", bgcolor: "#eaf3fb", color: "primary.main", "& .MuiSvgIcon-root": { fontSize: 35 } };
