import { useEffect, useState } from "react";
import { Alert, Box, IconButton, Paper, Stack, Typography } from "@mui/material";
import { useNavigate } from "react-router";
import AccountBalanceWalletRoundedIcon from "@mui/icons-material/AccountBalanceWalletRounded";
import DeleteRoundedIcon from "@mui/icons-material/DeleteRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import { Editor, ManagementShell } from "./CategoryManagementPage";
import { usePosApi } from "../../hooks/useApiResource";

const cash = { id: "cash", name: "Cash", detail: "Default cash payment", system: true };
export default function PaymentMethodManagementPage() { const navigate = useNavigate(); const api = usePosApi(); const [items, setItems] = useState([cash]); const [draft, setDraft] = useState(""); const [editing, setEditing] = useState(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const hydrate = async () => { try { const { settings } = await api.shop.getSettings(); setItems([cash, ...(settings.paymentMethods || []).filter((item) => item.id !== "cash").map((item) => ({ ...item, detail: "Custom payment method" }))]); } catch (err) { setError(err.message || "Payment methods could not be loaded."); } }; useEffect(() => { const timer = setTimeout(() => { void hydrate(); }, 0); return () => clearTimeout(timer); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [api]); const close = () => { setDraft(""); setEditing(null); }; const persist = async (next) => { setSaving(true); setError(""); try { const { settings } = await api.shop.updateSettings({ paymentMethods: next.filter((item) => !item.system).map((item, index) => ({ id: item.id, name: item.name, type: "normal", active: item.active !== false, sortOrder: index })) }); setItems([cash, ...(settings.paymentMethods || []).filter((item) => item.id !== "cash").map((item) => ({ ...item, detail: "Custom payment method" }))]); close(); } catch (err) { setError(err.message || "Payment method could not be saved."); } finally { setSaving(false); } }; const save = () => { const name = draft.trim(); if (!name) return; persist(editing?.id ? items.map((item) => item.id === editing.id ? { ...item, name } : item) : [...items, { id: `method-${crypto.randomUUID()}`, name, active: true, detail: "Custom payment method" }]); }; return <ManagementShell title="Payment Method" back={() => navigate("/settings")} button="Add Method" onAdd={() => setEditing({})}><Stack spacing={2.25}>{error && <Alert severity="error">{error}</Alert>}{items.map((item) => <Paper key={item.id} elevation={2} sx={cardSx}><Box sx={iconSx}><AccountBalanceWalletRoundedIcon /></Box><Box sx={{ minWidth: 0 }}><Typography sx={{ fontSize: 22, fontWeight: 700 }}>{item.name}</Typography><Typography color="text.secondary" sx={{ mt: .25, fontSize: 17 }}>{item.detail}</Typography></Box>{item.system ? <Box sx={{ width: 96 }} /> : <><IconButton aria-label={`Edit ${item.name}`} onClick={() => { setDraft(item.name); setEditing(item); }} sx={{ color: "primary.main" }}><EditRoundedIcon sx={{ fontSize: 31 }} /></IconButton><IconButton aria-label={`Delete ${item.name}`} onClick={() => persist(items.filter((entry) => entry.id !== item.id))} sx={{ color: "#ef5144" }}><DeleteRoundedIcon sx={{ fontSize: 31 }} /></IconButton></>}</Paper>)}</Stack><Editor open={Boolean(editing)} title={editing?.id ? "Edit Payment Method" : "Add Payment Method"} value={draft} onChange={setDraft} onClose={close} onSave={save} label={saving ? "Saving…" : "Payment method name"} /></ManagementShell>; }
const cardSx = { minHeight: 140, p: { xs: 2, sm: 2.75 }, borderRadius: 2.5, display: "grid", gridTemplateColumns: "72px minmax(0,1fr) 48px 48px", alignItems: "center", gap: { xs: 1.25, sm: 2 }, boxShadow: "0 3px 9px rgba(15,23,42,.19)" };
const iconSx = { width: 64, height: 64, borderRadius: "50%", display: "grid", placeItems: "center", bgcolor: "#eaf3fb", color: "primary.main", "& .MuiSvgIcon-root": { fontSize: 35 } };
