import { useState } from "react";
import { Box, IconButton, Paper, Stack, Typography } from "@mui/material";
import { useNavigate } from "react-router";
import AccountBalanceWalletRoundedIcon from "@mui/icons-material/AccountBalanceWalletRounded";
import DeleteRoundedIcon from "@mui/icons-material/DeleteRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import { Editor, ManagementShell } from "./CategoryManagementPage";

const initial = [{ id: 1, name: "Cash", detail: "Default cash payment" }, { id: 2, name: "KBZPay", detail: "Mobile wallet" }, { id: 3, name: "Bank Transfer", detail: "Bank account payment" }];
export default function PaymentMethodManagementPage() { const navigate = useNavigate(); const [items, setItems] = useState(initial); const [draft, setDraft] = useState(""); const [editing, setEditing] = useState(null); const close = () => { setDraft(""); setEditing(null); }; const save = () => { if (!draft.trim()) return; setItems((list) => editing?.id ? list.map((item) => item.id === editing.id ? { ...item, name: draft.trim() } : item) : [...list, { id: Date.now(), name: draft.trim(), detail: "Custom payment method" }]); close(); }; return <ManagementShell title="Payment Method" back={() => navigate("/settings")} button="Add Method" onAdd={() => setEditing({})}><Stack spacing={2.25}>{items.map((item) => <Paper key={item.id} elevation={2} sx={cardSx}><Box sx={iconSx}><AccountBalanceWalletRoundedIcon /></Box><Box sx={{ minWidth: 0 }}><Typography sx={{ fontSize: 22, fontWeight: 700 }}>{item.name}</Typography><Typography color="text.secondary" sx={{ mt: .25, fontSize: 17 }}>{item.detail}</Typography></Box><IconButton aria-label={`Edit ${item.name}`} onClick={() => { setDraft(item.name); setEditing(item); }} sx={{ color: "primary.main" }}><EditRoundedIcon sx={{ fontSize: 31 }} /></IconButton><IconButton aria-label={`Delete ${item.name}`} onClick={() => setItems((list) => list.filter((entry) => entry.id !== item.id))} sx={{ color: "#ef5144" }}><DeleteRoundedIcon sx={{ fontSize: 31 }} /></IconButton></Paper>)}</Stack><Editor open={Boolean(editing)} title={editing?.id ? "Edit Payment Method" : "Add Payment Method"} value={draft} onChange={setDraft} onClose={close} onSave={save} label="Payment method name" /></ManagementShell>; }
const cardSx = { minHeight: 140, p: { xs: 2, sm: 2.75 }, borderRadius: 2.5, display: "grid", gridTemplateColumns: "72px minmax(0,1fr) 48px 48px", alignItems: "center", gap: { xs: 1.25, sm: 2 }, boxShadow: "0 3px 9px rgba(15,23,42,.19)" };
const iconSx = { width: 64, height: 64, borderRadius: "50%", display: "grid", placeItems: "center", bgcolor: "#eaf3fb", color: "primary.main", "& .MuiSvgIcon-root": { fontSize: 35 } };
