import { useRef, useState } from "react";
import { useNavigate } from "react-router";
import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, IconButton, InputAdornment, Paper, Stack, Switch, TextField, Typography, useMediaQuery } from "@mui/material";
import AccountBalanceWalletRoundedIcon from "@mui/icons-material/AccountBalanceWalletRounded";
import AddAPhotoRoundedIcon from "@mui/icons-material/AddAPhotoRounded";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import AnalyticsRoundedIcon from "@mui/icons-material/AnalyticsRounded";
import CategoryRoundedIcon from "@mui/icons-material/CategoryRounded";
import ChevronRightRoundedIcon from "@mui/icons-material/ChevronRightRounded";
import CloudUploadRoundedIcon from "@mui/icons-material/CloudUploadRounded";
import ContactSupportRoundedIcon from "@mui/icons-material/ContactSupportRounded";
import CreditCardRoundedIcon from "@mui/icons-material/CreditCardRounded";
import CurrencyExchangeRoundedIcon from "@mui/icons-material/CurrencyExchangeRounded";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import FileDownloadRoundedIcon from "@mui/icons-material/FileDownloadRounded";
import FingerprintRoundedIcon from "@mui/icons-material/FingerprintRounded";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import LanguageRoundedIcon from "@mui/icons-material/LanguageRounded";
import LocalOfferRoundedIcon from "@mui/icons-material/LocalOfferRounded";
import LocalShippingRoundedIcon from "@mui/icons-material/LocalShippingRounded";
import LogoutRoundedIcon from "@mui/icons-material/LogoutRounded";
import LocationOnRoundedIcon from "@mui/icons-material/LocationOnRounded";
import NotificationsRoundedIcon from "@mui/icons-material/NotificationsRounded";
import PaletteRoundedIcon from "@mui/icons-material/PaletteRounded";
import PolicyRoundedIcon from "@mui/icons-material/PolicyRounded";
import StorefrontRoundedIcon from "@mui/icons-material/StorefrontRounded";
import WorkspacePremiumRoundedIcon from "@mui/icons-material/WorkspacePremiumRounded";
import { DesktopPanel } from "../../components/Desktop/DesktopUI";
import { useAppPreferences } from "../../context/AppPreferenceContext";
import { useAuth } from "../../context/AuthContext";

const mobileBusinessSettings = [
  { label: "Suppliers", icon: <LocalShippingRoundedIcon />, tone: "#38a5dd", path: "/suppliers" }, { label: "Payment", icon: <AccountBalanceWalletRoundedIcon />, tone: "#48ad60", path: "/payment" }, { label: "Reports & Analytics", icon: <AnalyticsRoundedIcon />, tone: "#a23bc0", path: "/report" }, { label: "Price & Promotion", icon: <LocalOfferRoundedIcon />, tone: "#ff9f1c", path: "/price" }, { label: "Shop Details", icon: <StorefrontRoundedIcon />, tone: "#2386ca", path: "/settings/shop-details" }, { label: "Categories", icon: <CategoryRoundedIcon />, tone: "#f6a31a", path: "/settings/categories" }, { label: "Payment Method", icon: <CreditCardRoundedIcon />, tone: "#2eafbd", path: "/settings/payment-methods" }, { label: "Premium", icon: <WorkspacePremiumRoundedIcon />, tone: "#a23bc0", trailing: <Chip label="Active" size="small" color="success" sx={{ borderRadius: 1, fontWeight: 700 }} /> }, { label: "Backup & Restore", icon: <CloudUploadRoundedIcon />, tone: "#16b6c7" }, { label: "Export Data", icon: <FileDownloadRoundedIcon />, tone: "#f26539" },
];
const aboutSettings = [{ label: "Contact Support", icon: <ContactSupportRoundedIcon />, tone: "#2997d7" }, { label: "Terms & Conditions", icon: <InfoOutlinedIcon />, tone: "#805f51" }, { label: "Privacy Policy", icon: <PolicyRoundedIcon />, tone: "#7959b5" }, { label: "App Version", icon: <InfoOutlinedIcon />, tone: "#607d86", value: "1.1.5" }];

export default function SettingsPage() {
  const isMobile = useMediaQuery("(max-width:768px)"); const navigate = useNavigate(); const { logout } = useAuth(); const { themeMode, setThemeMode, shop, setShop } = useAppPreferences();
  const [notifications, setNotifications] = useState(true); const [biometric, setBiometric] = useState(false); const [language, setLanguage] = useState("English"); const [currency, setCurrency] = useState("ကျပ်"); const [picker, setPicker] = useState(""); const [desktopModal, setDesktopModal] = useState(""); const [categories, setCategories] = useState([{ id: 1, name: "Drinking", detail: "1 product" }, { id: 2, name: "Food", detail: "0 products" }, { id: 3, name: "Medicine", detail: "1 product" }]); const [paymentMethods, setPaymentMethods] = useState([{ id: 1, name: "Cash", detail: "Default cash payment" }, { id: 2, name: "KBZPay", detail: "Mobile wallet" }, { id: 3, name: "Bank Transfer", detail: "Bank account payment" }]);
  const appSettings = [{ label: "Currency", icon: <CurrencyExchangeRoundedIcon />, tone: "#16a28c", value: currency, onClick: () => setPicker("currency") }, { label: "Language", icon: <LanguageRoundedIcon />, tone: "#4e5db1", value: language, onClick: () => setPicker("language") }, { label: "Theme", icon: <PaletteRoundedIcon />, tone: "#d52674", value: themeMode === "dark" ? "Dark Mode" : "Light Mode", onClick: () => setPicker("theme") }, { label: "Notification Settings", icon: <NotificationsRoundedIcon />, tone: "#f5b91c", trailing: <Chip label={notifications ? "ON" : "OFF"} size="small" color={notifications ? "success" : "default"} sx={{ borderRadius: 1, fontWeight: 700 }} />, onClick: () => setNotifications((value) => !value) }, { label: "Biometric Lock", icon: <FingerprintRoundedIcon />, tone: "#e26561", trailing: <Switch checked={biometric} onChange={(event) => setBiometric(event.target.checked)} sx={{ pointerEvents: "auto" }} /> }];
  const desktopBusinessSettings = [{ label: "Shop Details", icon: <StorefrontRoundedIcon />, tone: "#2386ca", onClick: () => setDesktopModal("shop") }, { label: "Categories", icon: <CategoryRoundedIcon />, tone: "#f6a31a", onClick: () => setDesktopModal("categories") }, { label: "Payment Method", icon: <CreditCardRoundedIcon />, tone: "#2eafbd", onClick: () => setDesktopModal("payment-methods") }, { label: "Premium", icon: <WorkspacePremiumRoundedIcon />, tone: "#a23bc0", trailing: <Chip label="Active" size="small" color="success" sx={{ borderRadius: 1, fontWeight: 700 }} /> }, { label: "Backup & Restore", icon: <CloudUploadRoundedIcon />, tone: "#16b6c7" }, { label: "Export Data", icon: <FileDownloadRoundedIcon />, tone: "#f26539" }];
  const desktopAppSettings = appSettings.filter((item) => item.label !== "Biometric Lock");
  const pickerProps = { open: Boolean(picker), type: picker, value: picker === "currency" ? currency : picker === "language" ? language : themeMode, onClose: () => setPicker(""), onSelect: (value) => { if (picker === "currency") setCurrency(value); if (picker === "language") setLanguage(value); if (picker === "theme") setThemeMode(value); setPicker(""); } };
  if (!isMobile) return <Box sx={{ maxWidth: 1440, mx: "auto", py: 1 }}><Stack spacing={2.5}><DesktopSettingsGroup title="Business" rows={desktopBusinessSettings} columns={3} navigate={navigate} /><DesktopSettingsGroup title="App Settings" rows={desktopAppSettings} columns={4} navigate={navigate} /><DesktopSettingsGroup title="About" rows={aboutSettings} columns={4} navigate={navigate} /></Stack><Picker {...pickerProps} /><DesktopShopDetailsDialog open={desktopModal === "shop"} onClose={() => setDesktopModal("")} shop={shop} setShop={setShop} /><DesktopManagementDialog open={desktopModal === "categories"} onClose={() => setDesktopModal("")} title="Category Management" itemLabel="Category" items={categories} setItems={setCategories} icon={<CategoryRoundedIcon />} /><DesktopManagementDialog open={desktopModal === "payment-methods"} onClose={() => setDesktopModal("")} title="Payment Method" itemLabel="Payment Method" items={paymentMethods} setItems={setPaymentMethods} icon={<CreditCardRoundedIcon />} /></Box>;
  return <Box sx={{ px: 3, pt: 3, pb: 2, bgcolor: "background.default" }}><Section title="Business" rows={mobileBusinessSettings} navigate={navigate} /><Section title="App Settings" rows={appSettings} navigate={navigate} /><Section title="About" rows={aboutSettings} navigate={navigate} /><Button fullWidth variant="outlined" startIcon={<LogoutRoundedIcon />} onClick={() => void logout()} sx={{ minHeight: 56, mt: -1, mb: 2, borderColor: "error.main", color: "error.main", fontSize: 17, fontWeight: 700, textTransform: "none" }}>Logout</Button><Picker {...pickerProps} /></Box>;
}
function Section({ title, rows, navigate }) { return <Box sx={{ mb: 3.25 }}><Typography color="text.secondary" sx={{ fontSize: 20, fontWeight: 700, mb: 1.75, pl: .75 }}>{title}</Typography><Paper elevation={0} sx={{ overflow: "hidden", borderRadius: 3, bgcolor: "background.paper", boxShadow: "0 3px 9px rgba(15,23,42,.15)" }}>{rows.map((row, index) => <Box key={row.label}><Row row={row} navigate={navigate} />{index < rows.length - 1 && <Divider sx={{ ml: 11.25 }} />}</Box>)}</Paper></Box>; }
function Row({ row, navigate }) { const trailing = row.trailing ?? (row.value ? <Typography color="text.secondary" sx={{ fontSize: 16 }}>{row.value}</Typography> : <ChevronRightRoundedIcon sx={{ color: "#b4b4b4", fontSize: 31 }} />); return <Box role="button" tabIndex={0} onClick={() => row.onClick ? row.onClick() : row.path && navigate(row.path === "/report" ? "/report/sales" : row.path)} sx={{ minHeight: 103, px: 2.5, display: "grid", gridTemplateColumns: "64px minmax(0,1fr) auto", alignItems: "center", columnGap: 1.5, cursor: row.path || row.onClick ? "pointer" : "default", "&:hover": { bgcolor: "action.hover" } }}><Box sx={{ width: 64, height: 64, borderRadius: 2, display: "grid", placeItems: "center", bgcolor: `${row.tone}16`, color: row.tone, "& .MuiSvgIcon-root": { fontSize: 33 } }}>{row.icon}</Box><Typography sx={{ fontSize: 21, fontWeight: 600 }}>{row.label}</Typography><Box onClick={(event) => event.stopPropagation()}>{trailing}</Box></Box>; }
function DesktopSettingsGroup({ title, rows, columns, navigate }) { return <DesktopPanel sx={{ "& .MuiCardContent-root": { p: 2.5, "&:last-child": { pb: 2.5 } } }}><Typography sx={{ mb: 1.75, fontSize: 19, fontWeight: 750 }}>{title}</Typography><Box sx={{ display: "grid", gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))`, gap: 1.25 }}>{rows.map((row) => <Box key={row.label} role={row.onClick || row.path ? "button" : undefined} tabIndex={row.onClick || row.path ? 0 : undefined} onClick={() => row.onClick ? row.onClick() : row.path && navigate(row.path)} sx={{ minHeight: 88, px: 1.5, display: "grid", gridTemplateColumns: "40px minmax(0, 1fr) auto", alignItems: "center", columnGap: 1.15, border: "1px solid", borderColor: "divider", borderRadius: 1.75, bgcolor: "background.default", cursor: row.onClick || row.path ? "pointer" : "default", transition: "background-color 150ms ease, border-color 150ms ease", "&:hover": row.onClick || row.path ? { bgcolor: "action.hover", borderColor: "primary.light" } : {} }}><Box sx={{ width: 36, height: 36, display: "grid", placeItems: "center", borderRadius: 1.25, bgcolor: `${row.tone}16`, color: row.tone }}>{row.icon}</Box><Typography noWrap sx={{ fontSize: 14, fontWeight: 700 }}>{row.label}</Typography>{row.trailing ?? (row.value ? <Typography noWrap color="text.secondary" sx={{ fontSize: 13 }}>{row.value}</Typography> : (row.onClick || row.path ? <ChevronRightRoundedIcon color="disabled" sx={{ fontSize: 19 }} /> : null))}</Box>)}</Box></DesktopPanel>; }
function Picker({ open, type, value, onClose, onSelect }) { const options = type === "language" ? ["English", "Myanmar", "Chinese"] : type === "currency" ? ["ကျပ်", "ထိုင်းဘတ်", "Dollar"] : [{ label: "Light Mode", value: "light" }, { label: "Dark Mode", value: "dark" }]; return <Dialog open={open} onClose={onClose} fullWidth slotProps={{ paper: { sx: { m: 2.5, borderRadius: 2.5, maxWidth: 420 } } }}><DialogTitle sx={{ fontWeight: 700 }}>Choose {type === "theme" ? "theme" : type}</DialogTitle><DialogContent sx={{ pt: "8px !important", pb: 2.5 }}><Box sx={{ display: "grid", gap: 1 }}>{options.map((option) => { const item = typeof option === "string" ? { label: option, value: option } : option; return <Button key={item.value} variant={value === item.value ? "contained" : "outlined"} onClick={() => onSelect(item.value)} sx={{ minHeight: 52, justifyContent: "flex-start", px: 2, borderRadius: 1.5, fontSize: 16, fontWeight: 600, textTransform: "none" }}>{item.label}</Button>; })}</Box></DialogContent></Dialog>; }
function DesktopShopDetailsDialog({ open, onClose, shop, setShop }) { const [form, setForm] = useState(shop); const fileRef = useRef(null); const change = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value })); const chooseLogo = (event) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setForm((current) => ({ ...current, logo: String(reader.result) })); reader.readAsDataURL(file); }; const save = () => { setShop({ ...form, name: form.name.trim() || "POS System" }); onClose(); }; return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm" slotProps={{ paper: { sx: { borderRadius: 2.5 } } }}><DialogTitle sx={{ fontWeight: 800 }}>Edit Shop Details</DialogTitle><DialogContent dividers><Stack spacing={2.25}><Box sx={{ display: "flex", alignItems: "center", gap: 2 }}><Box role="button" tabIndex={0} onClick={() => fileRef.current?.click()} onKeyDown={(event) => event.key === "Enter" && fileRef.current?.click()} sx={{ width: 88, height: 88, flexShrink: 0, borderRadius: "50%", overflow: "hidden", border: "2px solid", borderColor: "divider", bgcolor: "action.hover", display: "grid", placeItems: "center", cursor: "pointer", color: "text.secondary" }}>{form.logo ? <Box component="img" src={form.logo} alt="Shop logo preview" sx={{ width: "100%", height: "100%", objectFit: "cover" }} /> : <AddAPhotoRoundedIcon sx={{ fontSize: 36 }} />}</Box><Button startIcon={<AddAPhotoRoundedIcon />} onClick={() => fileRef.current?.click()} sx={{ textTransform: "none", fontWeight: 700 }}>{form.logo ? "Change Shop Logo" : "Add Shop Logo"}</Button><input ref={fileRef} type="file" accept="image/*" hidden onChange={chooseLogo} /></Box><TextField label="Shop Name" value={form.name} onChange={change("name")} fullWidth slotProps={{ input: { startAdornment: <InputAdornment position="start"><StorefrontRoundedIcon /></InputAdornment> } }} /><TextField label="Address" value={form.address} onChange={change("address")} fullWidth multiline minRows={3} slotProps={{ input: { startAdornment: <InputAdornment position="start"><LocationOnRoundedIcon /></InputAdornment> } }} /></Stack></DialogContent><DialogActions sx={{ px: 3, py: 1.5 }}><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={save}>Update Shop</Button></DialogActions></Dialog>; }
function DesktopManagementDialog({ open, onClose, title, itemLabel, items, setItems, icon }) { const [draft, setDraft] = useState(""); const [editing, setEditing] = useState(null); const closeEditor = () => { setDraft(""); setEditing(null); }; const save = () => { const name = draft.trim(); if (!name) return; setItems((current) => editing ? current.map((item) => item.id === editing.id ? { ...item, name } : item) : [...current, { id: Date.now(), name, detail: itemLabel === "Category" ? "0 products" : "Custom payment method" }]); closeEditor(); }; return <Dialog open={open} onClose={() => { closeEditor(); onClose(); }} fullWidth maxWidth="sm" slotProps={{ paper: { sx: { borderRadius: 2.5 } } }}><DialogTitle sx={{ fontWeight: 800 }}>{title}</DialogTitle><DialogContent dividers><Stack spacing={1.25}>{items.map((item) => <Paper key={item.id} variant="outlined" sx={{ px: 1.5, py: 1.25, display: "grid", gridTemplateColumns: "42px minmax(0, 1fr) auto auto", alignItems: "center", gap: 1 }}><Box sx={{ width: 36, height: 36, display: "grid", placeItems: "center", borderRadius: 1.25, color: "primary.main", bgcolor: "#eaf3ff" }}>{icon}</Box><Box><Typography fontWeight={700}>{item.name}</Typography><Typography color="text.secondary" sx={{ fontSize: 13 }}>{item.detail}</Typography></Box><IconButton aria-label={`Edit ${item.name}`} onClick={() => { setDraft(item.name); setEditing(item); }} color="primary"><EditOutlinedIcon /></IconButton><IconButton aria-label={`Delete ${item.name}`} onClick={() => setItems((current) => current.filter((entry) => entry.id !== item.id))} color="error"><DeleteOutlineRoundedIcon /></IconButton></Paper>)}</Stack><Box sx={{ display: "flex", justifyContent: "flex-end", mt: 2 }}><Button variant="outlined" startIcon={<AddRoundedIcon />} onClick={() => setEditing({})} sx={{ textTransform: "none", fontWeight: 700 }}>Add {itemLabel}</Button></Box></DialogContent><DialogActions sx={{ px: 3, py: 1.5 }}><Button onClick={() => { closeEditor(); onClose(); }}>Close</Button></DialogActions><Dialog open={Boolean(editing)} onClose={closeEditor} fullWidth maxWidth="xs" slotProps={{ paper: { sx: { borderRadius: 2 } } }}><DialogTitle sx={{ fontWeight: 700 }}>{editing?.id ? `Edit ${itemLabel}` : `Add ${itemLabel}`}</DialogTitle><DialogContent><TextField autoFocus fullWidth label={`${itemLabel} name`} value={draft} onChange={(event) => setDraft(event.target.value)} sx={{ mt: .5 }} /></DialogContent><DialogActions sx={{ px: 3, py: 1.5 }}><Button onClick={closeEditor}>Cancel</Button><Button variant="contained" onClick={save}>Save</Button></DialogActions></Dialog></Dialog>; }
