import { useState } from "react";
import { useNavigate } from "react-router";
import { Box, Button, Chip, Dialog, DialogContent, DialogTitle, Divider, Paper, Switch, Typography, useMediaQuery } from "@mui/material";
import AccountBalanceWalletRoundedIcon from "@mui/icons-material/AccountBalanceWalletRounded";
import AnalyticsRoundedIcon from "@mui/icons-material/AnalyticsRounded";
import CategoryRoundedIcon from "@mui/icons-material/CategoryRounded";
import ChevronRightRoundedIcon from "@mui/icons-material/ChevronRightRounded";
import CloudUploadRoundedIcon from "@mui/icons-material/CloudUploadRounded";
import ContactSupportRoundedIcon from "@mui/icons-material/ContactSupportRounded";
import CreditCardRoundedIcon from "@mui/icons-material/CreditCardRounded";
import CurrencyExchangeRoundedIcon from "@mui/icons-material/CurrencyExchangeRounded";
import FileDownloadRoundedIcon from "@mui/icons-material/FileDownloadRounded";
import FingerprintRoundedIcon from "@mui/icons-material/FingerprintRounded";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import LanguageRoundedIcon from "@mui/icons-material/LanguageRounded";
import LocalOfferRoundedIcon from "@mui/icons-material/LocalOfferRounded";
import LocalShippingRoundedIcon from "@mui/icons-material/LocalShippingRounded";
import NotificationsRoundedIcon from "@mui/icons-material/NotificationsRounded";
import PaletteRoundedIcon from "@mui/icons-material/PaletteRounded";
import PolicyRoundedIcon from "@mui/icons-material/PolicyRounded";
import StorefrontRoundedIcon from "@mui/icons-material/StorefrontRounded";
import WorkspacePremiumRoundedIcon from "@mui/icons-material/WorkspacePremiumRounded";
import { DesktopPage, DesktopPanel } from "../../components/Desktop/DesktopUI";
import { useAppPreferences } from "../../AppProvider";

const businessSettings = [
  { label: "Suppliers", icon: <LocalShippingRoundedIcon />, tone: "#38a5dd", path: "/suppliers" }, { label: "Payment", icon: <AccountBalanceWalletRoundedIcon />, tone: "#48ad60", path: "/payment" }, { label: "Reports & Analytics", icon: <AnalyticsRoundedIcon />, tone: "#a23bc0", path: "/report" }, { label: "Price & Promotion", icon: <LocalOfferRoundedIcon />, tone: "#ff9f1c", path: "/price" }, { label: "Shop Details", icon: <StorefrontRoundedIcon />, tone: "#2386ca", path: "/settings/shop-details" }, { label: "Categories", icon: <CategoryRoundedIcon />, tone: "#f6a31a", path: "/settings/categories" }, { label: "Payment Method", icon: <CreditCardRoundedIcon />, tone: "#2eafbd", path: "/settings/payment-methods" }, { label: "Premium", icon: <WorkspacePremiumRoundedIcon />, tone: "#a23bc0", trailing: <Chip label="Active" size="small" color="success" sx={{ borderRadius: 1, fontWeight: 700 }} /> }, { label: "Backup & Restore", icon: <CloudUploadRoundedIcon />, tone: "#16b6c7" }, { label: "Export Data", icon: <FileDownloadRoundedIcon />, tone: "#f26539" },
];
const aboutSettings = [{ label: "Contact Support", icon: <ContactSupportRoundedIcon />, tone: "#2997d7" }, { label: "Terms & Conditions", icon: <InfoOutlinedIcon />, tone: "#805f51" }, { label: "Privacy Policy", icon: <PolicyRoundedIcon />, tone: "#7959b5" }, { label: "App Version", icon: <InfoOutlinedIcon />, tone: "#607d86", value: "1.1.5" }];

export default function SettingsPage() {
  const isMobile = useMediaQuery("(max-width:768px)"); const navigate = useNavigate(); const { themeMode, setThemeMode } = useAppPreferences();
  const [notifications, setNotifications] = useState(true); const [biometric, setBiometric] = useState(false); const [language, setLanguage] = useState("English"); const [currency, setCurrency] = useState("ကျပ်"); const [picker, setPicker] = useState("");
  const appSettings = [{ label: "Currency", icon: <CurrencyExchangeRoundedIcon />, tone: "#16a28c", value: currency, onClick: () => setPicker("currency") }, { label: "Language", icon: <LanguageRoundedIcon />, tone: "#4e5db1", value: language, onClick: () => setPicker("language") }, { label: "Theme", icon: <PaletteRoundedIcon />, tone: "#d52674", value: themeMode === "dark" ? "Dark Mode" : "Light Mode", onClick: () => setPicker("theme") }, { label: "Notification Settings", icon: <NotificationsRoundedIcon />, tone: "#f5b91c", trailing: <Chip label={notifications ? "ON" : "OFF"} size="small" color={notifications ? "success" : "default"} sx={{ borderRadius: 1, fontWeight: 700 }} />, onClick: () => setNotifications((value) => !value) }, { label: "Biometric Lock", icon: <FingerprintRoundedIcon />, tone: "#e26561", trailing: <Switch checked={biometric} onChange={(event) => setBiometric(event.target.checked)} sx={{ pointerEvents: "auto" }} /> }];
  if (!isMobile) return <DesktopPage title="Settings" subtitle="Manage your store and application preferences."><Box sx={{ display: "grid", gridTemplateColumns: "1.25fr .75fr", gap: 3 }}><DesktopCard title="Business" rows={businessSettings} navigate={navigate} /><Box sx={{ display: "grid", gap: 3, alignContent: "start" }}><DesktopCard title="App Settings" rows={appSettings} navigate={navigate} /><DesktopCard title="About" rows={aboutSettings} navigate={navigate} /></Box></Box><Picker open={Boolean(picker)} type={picker} value={picker === "currency" ? currency : picker === "language" ? language : themeMode} onClose={() => setPicker("")} onSelect={(value) => { if (picker === "currency") setCurrency(value); if (picker === "language") setLanguage(value); if (picker === "theme") setThemeMode(value); setPicker(""); }} /></DesktopPage>;
  return <Box sx={{ px: 3, pt: 3, pb: 2, bgcolor: "background.default" }}><Section title="Business" rows={businessSettings} navigate={navigate} /><Section title="App Settings" rows={appSettings} navigate={navigate} /><Section title="About" rows={aboutSettings} navigate={navigate} /><Picker open={Boolean(picker)} type={picker} value={picker === "currency" ? currency : picker === "language" ? language : themeMode} onClose={() => setPicker("")} onSelect={(value) => { if (picker === "currency") setCurrency(value); if (picker === "language") setLanguage(value); if (picker === "theme") setThemeMode(value); setPicker(""); }} /></Box>;
}
function Section({ title, rows, navigate }) { return <Box sx={{ mb: 3.25 }}><Typography color="text.secondary" sx={{ fontSize: 20, fontWeight: 700, mb: 1.75, pl: .75 }}>{title}</Typography><Paper elevation={0} sx={{ overflow: "hidden", borderRadius: 3, bgcolor: "background.paper", boxShadow: "0 3px 9px rgba(15,23,42,.15)" }}>{rows.map((row, index) => <Box key={row.label}><Row row={row} navigate={navigate} />{index < rows.length - 1 && <Divider sx={{ ml: 11.25 }} />}</Box>)}</Paper></Box>; }
function Row({ row, navigate }) { const trailing = row.trailing ?? (row.value ? <Typography color="text.secondary" sx={{ fontSize: 16 }}>{row.value}</Typography> : <ChevronRightRoundedIcon sx={{ color: "#b4b4b4", fontSize: 31 }} />); return <Box role="button" tabIndex={0} onClick={() => row.onClick ? row.onClick() : row.path && navigate(row.path)} sx={{ minHeight: 103, px: 2.5, display: "grid", gridTemplateColumns: "64px minmax(0,1fr) auto", alignItems: "center", columnGap: 1.5, cursor: row.path || row.onClick ? "pointer" : "default", "&:hover": { bgcolor: "action.hover" } }}><Box sx={{ width: 64, height: 64, borderRadius: 2, display: "grid", placeItems: "center", bgcolor: `${row.tone}16`, color: row.tone, "& .MuiSvgIcon-root": { fontSize: 33 } }}>{row.icon}</Box><Typography sx={{ fontSize: 21, fontWeight: 600 }}>{row.label}</Typography><Box onClick={(event) => event.stopPropagation()}>{trailing}</Box></Box>; }
function DesktopCard({ title, rows, navigate }) { return <DesktopPanel><Typography sx={{ fontSize: 19, fontWeight: 700, mb: 1 }}>{title}</Typography>{rows.map((row, index) => <Box key={row.label}><Box onClick={() => row.onClick ? row.onClick() : row.path && navigate(row.path)} sx={{ minHeight: 70, display: "grid", gridTemplateColumns: "46px minmax(0,1fr) auto", alignItems: "center", columnGap: 1.5, cursor: row.path || row.onClick ? "pointer" : "default" }}><Box sx={{ width: 40, height: 40, display: "grid", placeItems: "center", borderRadius: 1.5, bgcolor: `${row.tone}16`, color: row.tone }}>{row.icon}</Box><Typography sx={{ fontWeight: 600 }}>{row.label}</Typography>{row.trailing ?? (row.value ? <Typography color="text.secondary">{row.value}</Typography> : <ChevronRightRoundedIcon color="disabled" />)}</Box>{index < rows.length - 1 && <Divider />}</Box>)}</DesktopPanel>; }
function Picker({ open, type, value, onClose, onSelect }) { const options = type === "language" ? ["English", "Myanmar", "Chinese"] : type === "currency" ? ["ကျပ်", "ထိုင်းဘတ်", "Dollar"] : [{ label: "Light Mode", value: "light" }, { label: "Dark Mode", value: "dark" }]; return <Dialog open={open} onClose={onClose} fullWidth slotProps={{ paper: { sx: { m: 2.5, borderRadius: 2.5, maxWidth: 420 } } }}><DialogTitle sx={{ fontWeight: 700 }}>Choose {type === "theme" ? "theme" : type}</DialogTitle><DialogContent sx={{ pt: "8px !important", pb: 2.5 }}><Box sx={{ display: "grid", gap: 1 }}>{options.map((option) => { const item = typeof option === "string" ? { label: option, value: option } : option; return <Button key={item.value} variant={value === item.value ? "contained" : "outlined"} onClick={() => onSelect(item.value)} sx={{ minHeight: 52, justifyContent: "flex-start", px: 2, borderRadius: 1.5, fontSize: 16, fontWeight: 600, textTransform: "none" }}>{item.label}</Button>; })}</Box></DialogContent></Dialog>; }
