export const queryKeys = {
  dashboard: (shopId) => ["shops", shopId, "dashboard"],
  products: (shopId, query = {}) => ["shops", shopId, "products", query],
  product: (shopId, productId) => ["shops", shopId, "products", productId],
  categories: (shopId) => ["shops", shopId, "categories"],
  units: (shopId) => ["shops", shopId, "units"],
  inventory: (shopId, query = {}) => ["shops", shopId, "inventory", query],
  movements: (shopId, query = {}) => ["shops", shopId, "movements", query],
  orders: (shopId, query = {}) => ["shops", shopId, "orders", query],
  order: (shopId, orderId) => ["shops", shopId, "orders", orderId],
  shopDetails: (shopId) => ["shops", shopId, "details"],
  settings: (shopId) => ["shops", shopId, "settings"],
  pricing: (shopId, query = {}) => ["shops", shopId, "pricing", query],
  promotionCampaigns: (shopId) => ["shops", shopId, "promotion-campaigns"],
  supplierDeliveries: (shopId, query = {}) => ["shops", shopId, "supplier-deliveries", query],
  suppliers: (shopId, query = {}) => ["shops", shopId, "suppliers", query],
  payments: (shopId, query = {}) => ["shops", shopId, "payments", query],
  reports: (shopId, name, query = {}) => ["shops", shopId, "reports", name, query],
};
